from . import mlp
from . import lenet
from . import resnet
from . import senet
from . import cifar10net
from . import resnet_with_proj
from . import CNN
from . import resnet_with_proj2
from . import resnet_with_proj3
from . import alexnet